[package]
name = "example_node"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "minimal_pub"
path = "src/main.rs"

[dependencies]
rclrs = { version = "0.3" }
rosidl_runtime_rs = { version = "0.3" }
std_msgs = { path = '/workspaces/turtelism/install/share/std_msgs/rust' }
anyhow = "1.0"
